cognisleServerless:
  component: '@sls-next/serverless-component@latest'
  inputs:
    runtime:
      defaultLambda: "nodejs14.x"
      apiLambda: "nodejs14.x"
      imageLambda: "nodejs14.x"
    bucketName: 'cognisle'
    name:
      defaultLambda: DefaultLambda	#Default Lambda의 이름 설정 
      imageLambda: ImageLambda	# Image Lambda의 이름 설정
    bucketRegion: 'ap-northeast-2'	# S3 Bucket 지역 설정
    cloudfront:
      comment: 'next deploy'	# CloudFront 설명 설정
      distributionId: 'E2FZ4XSI3LM2WG'